### ISSUE TITLE
Conflict with ClaustOrephobic (no gate UI)

### ISSUE THREAD

**Issue by kholto** [PreLeyZero/exotic-industries#51]
With the mod ClaustOrephobic by Braxbro enabled the Gate building does not have a UI when clicked.

Instead of the intended UI there is simply a picture of the gate:
![billede](https://github.com/PreLeyZero/exotic-industries/assets/7372282/e9e48a40-32eb-4439-b604-ac8d353be8e8)

To reproduce: Enable ClaustOrephobic and Exotic Industries (even just the main mod), build a gate and click on it.

I believe Braxo will comment with some of his findings, as he took a look if the issue could be fixed from his side.

**Comment by kholto** [comment]
It is up to you if you want to fix this of cause, but if you do not it might be good to add ClaustOrephobic as a specific incompatibility as it takes quite a while before the player unlocks the gate with this mod combination and there is no warning of the issue beforehand.

**Comment by Braxbro** [comment]
Dev of ClaustOrephobic here:
I, unfortunately, can't fix this one from my end.

Right now, anything that modifies the collision mask of the gate entity breaks it. The only fix I could find on my end was excluding the gate itself (and its container) entirely from my mod's collision mask modification. Which is possible, come v1.1.6 of ClaustOrephobic, through the Claustorephobic::allowed_entity_names global table, as a temporary fix.

After looking at your code, I have no idea why this is. In v1.1.5, your gate-container should have the same collision mask as the container even without my modification: layers item-layer, layer-13, object-layer, player-layer, and water-tile. 

My mod adds layer-14 to that, because it's the earliest unreserved layer. In v1.1.6, it tries to add it to only the gate (electric energy interface) and not the container, because the container isn't placeable by anything. Either one breaks the gate, somehow.

**Comment by Braxbro** [comment]
https://github.com/Braxbro/zzz-claustorephobic/releases/tag/v1.1.6

Released, and fixed.

**Comment by Braxbro** [comment]
Reverted my gate fix, since the issue was fixed in v0.5.8.
